server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ride_fast_db
    username: root
    password: Yogendhra@L9
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true